In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import datetime
from datetime import datetime, timedelta
from sklearn.linear_model import LinearRegression,LogisticRegression

%matplotlib inline

In [2]:
df = pd.read_csv("DOHMH_New_York_City_Restaurant_Inspection_Results2.csv")

In [3]:
df.shape

(385226, 26)

In [4]:
df.columns

Index(['CAMIS', 'DBA', 'BORO', 'BUILDING', 'STREET', 'ZIPCODE', 'PHONE',
       'CUISINE DESCRIPTION', 'INSPECTION DATE', 'ACTION', 'VIOLATION CODE',
       'VIOLATION DESCRIPTION', 'CRITICAL FLAG', 'SCORE', 'GRADE',
       'GRADE DATE', 'RECORD DATE', 'INSPECTION TYPE', 'Latitude', 'Longitude',
       'Community Board', 'Council District', 'Census Tract', 'BIN', 'BBL',
       'NTA'],
      dtype='object')

In [6]:
df = df.drop(columns=['PHONE', 'BIN', 'BBL', 'NTA', 'Community Board', 'Council District', 'RECORD DATE'])

In [7]:
df.tail(2)

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,VIOLATION DESCRIPTION,CRITICAL FLAG,SCORE,GRADE,GRADE DATE,INSPECTION TYPE,Latitude,Longitude,Census Tract
385224,40575519,MOLYVOS,Manhattan,871,7 AVENUE,10019.0,Greek,03/20/2017,Violations were cited in the following area(s).,08C,Pesticide use not in accordance with label or ...,N,20.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.764567,-73.980712,13700.0
385225,50067280,LUCKY RESTAURANT,Queens,4521,PARSONS BLVD,11355.0,Chinese,12/26/2018,Violations were cited in the following area(s).,08A,Facility not vermin proof. Harborage or condit...,N,25.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.755241,-73.815033,118900.0

In [8]:
df['INSPECTION YEAR'] = df['INSPECTION DATE'].str.extract(r"/(\w+)$")

In [10]:
df['INSPECTION YEAR'] = df['INSPECTION YEAR'].str.replace('1900','not insprected yet')

In [ ]:
df['IN-DATE'] =  pd.to_datetime(df['INSPECTION DATE'])

In [11]:
df['INSPECTION YEAR'].value_counts().sort_index()

2013                       3
2014                      12
2015                    3944
2016                   62012
2017                   89473
2018                  133779
2019                   94670
not insprected yet      1333
Name: INSPECTION YEAR, dtype: int64

In [35]:
# df_viocode = df[['VIOLATION CODE', 'VIOLATION DESCRIPTION']]

In [36]:
# df_viocode.to_csv('df_viocode.csv')

In [38]:
df_viocode = pd.read_csv("df_viocode.csv")

In [46]:
df.shape

(385226, 21)

In [51]:
df18 = df[df['INSPECTION YEAR'] == '2018']

In [101]:
df18.to_csv('df18.csv')

In [102]:
df18 = pd.read_csv("df18.csv")

In [16]:
df[df['CAMIS'] == 41187577].sort_values(by='IN-DATE', ascending=False)

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,...,CRITICAL FLAG,SCORE,GRADE,GRADE DATE,INSPECTION TYPE,Latitude,Longitude,Census Tract,INSPECTION YEAR,IN-DATE
95032,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,06/12/2019,Violations were cited in the following area(s).,06B,...,Y,36.0,C,06/12/2019,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2019,2019-06-12
312352,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,06/12/2019,Violations were cited in the following area(s).,02G,...,Y,36.0,C,06/12/2019,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2019,2019-06-12
283704,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,06/12/2019,Violations were cited in the following area(s).,10H,...,N,36.0,C,06/12/2019,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2019,2019-06-12
255213,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,06/12/2019,Violations were cited in the following area(s).,09B,...,N,36.0,C,06/12/2019,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2019,2019-06-12
246766,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,06/12/2019,Violations were cited in the following area(s).,09C,...,N,36.0,C,06/12/2019,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2019,2019-06-12
32223,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,06/12/2019,Violations were cited in the following area(s).,02B,...,Y,36.0,C,06/12/2019,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2019,2019-06-12
177055,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,06/12/2019,Violations were cited in the following area(s).,10B,...,N,36.0,C,06/12/2019,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2019,2019-06-12
225452,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,06/12/2019,Violations were cited in the following area(s).,02C,...,Y,36.0,C,06/12/2019,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2019,2019-06-12
200541,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,04/09/2019,Violations were cited in the following area(s).,06A,...,Y,42.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2019,2019-04-09
112382,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,04/09/2019,Violations were cited in the following area(s).,02B,...,Y,42.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2019,2019-04-09
79158,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,04/09/2019,Violations were cited in the following area(s).,10H,...,N,42.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2019,2019-04-09
337485,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,04/09/2019,Violations were cited in the following area(s).,08A,...,N,42.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2019,2019-04-09
335841,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,04/09/2019,Violations were cited in the following area(s).,04M,...,Y,42.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2019,2019-04-09
88920,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,04/09/2019,Violations were cited in the following area(s).,04K,...,Y,42.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2019,2019-04-09
261517,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,04/09/2019,Violations were cited in the following area(s).,06C,...,Y,42.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2019,2019-04-09
340270,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,04/09/2019,Violations were cited in the following area(s).,02H,...,Y,42.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2019,2019-04-09
34989,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,04/09/2019,Violations were cited in the following area(s).,10B,...,N,42.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2019,2019-04-09
360547,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,12/04/2018,Violations were cited in the following area(s).,08A,...,N,21.0,B,12/04/2018,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2018,2018-12-04
130051,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,12/04/2018,Violations were cited in the following area(s).,04N,...,Y,21.0,B,12/04/2018,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2018,2018-12-04
317222,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,12/04/2018,Violations were cited in the following area(s).,10H,...,N,21.0,B,12/04/2018,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2018,2018-12-04
362510,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,12/04/2018,Violations were cited in the following area(s).,09B,...,N,21.0,B,12/04/2018,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2018,2018-12-04
51825,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,12/04/2018,Violations were cited in the following area(s).,02G,...,Y,21.0,B,12/04/2018,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2018,2018-12-04
91207,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,11/08/2018,Violations were cited in the following area(s).,04N,...,Y,30.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2018,2018-11-08
262750,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,11/08/2018,Violations were cited in the following area(s).,06F,...,Y,30.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2018,2018-11-08
99061,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,11/08/2018,Violations were cited in the following area(s).,10A,...,N,30.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2018,2018-11-08
24169,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,11/08/2018,Violations were cited in the following area(s).,04M,...,Y,30.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2018,2018-11-08
371839,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,11/08/2018,Violations were cited in the following area(s).,06C,...,Y,30.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2018,2018-11-08
130092,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,11/08/2018,Violations were cited in the following area(s).,06E,...,Y,30.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2018,2018-11-08
278647,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,11/08/2018,Violations were cited in the following area(s).,08A,...,N,30.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2018,2018-11-08
56503,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,10/09/2018,Violations were cited in the following area(s).,20F,...,N,NaN,NaN,NaN,Administrative Miscellaneous / Initial Inspection,40.762775,-73.805229,117100.0,2018,2018-10-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6910,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,06/18/2018,Establishment Closed by DOHMH. Violations wer...,08A,...,N,54.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2018,2018-06-18
264969,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,06/18/2018,Establishment Closed by DOHMH. Violations wer...,04K,...,Y,54.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2018,2018-06-18
150181,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,03/19/2018,Violations were cited in the following area(s).,08A,...,N,14.0,B,03/19/2018,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2018,2018-03-19
197778,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,03/19/2018,Violations were cited in the following area(s).,10F,...,N,14.0,B,03/19/2018,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2018,2018-03-19
11229,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,03/19/2018,Violations were cited in the following area(s).,04N,...,Y,14.0,B,03/19/2018,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2018,2018-03-19
293957,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,01/30/2018,Violations were cited in the following area(s).,06C,...,Y,21.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2018,2018-01-30
10831,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,01/30/2018,Violations were cited in the following area(s).,02G,...,Y,21.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2018,2018-01-30
219732,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,01/30/2018,Violations were cited in the following area(s).,10B,...,N,21.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2018,2018-01-30
26470,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,01/30/2018,Violations were cited in the following area(s).,08C,...,N,21.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2018,2018-01-30
237761,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,01/30/2018,Violations were cited in the following area(s).,10F,...,N,21.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2018,2018-01-30
6635,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,09/13/2017,No violations were recorded at the time of thi...,NaN,...,NaN,NaN,NaN,NaN,Administrative Miscellaneous / Initial Inspection,40.762775,-73.805229,117100.0,2017,2017-09-13
21714,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,04/05/2017,Violations were cited in the following area(s).,04M,...,Y,17.0,B,04/05/2017,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2017,2017-04-05
176150,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,04/05/2017,Violations were cited in the following area(s).,06D,...,Y,17.0,B,04/05/2017,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2017,2017-04-05
170473,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,04/05/2017,Violations were cited in the following area(s).,08A,...,N,17.0,B,04/05/2017,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2017,2017-04-05
275584,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,03/21/2017,Violations were cited in the following area(s).,04M,...,Y,23.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2017,2017-03-21
283529,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,03/21/2017,Violations were cited in the following area(s).,02H,...,Y,23.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2017,2017-03-21
13657,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,03/21/2017,Violations were cited in the following area(s).,08A,...,N,23.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2017,2017-03-21
51399,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,03/21/2017,Violations were cited in the following area(s).,04N,...,Y,23.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2017,2017-03-21
207960,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,03/21/2017,Violations were cited in the following area(s).,09B,...,N,23.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2017,2017-03-21
136253,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,03/21/2017,Violations were cited in the following area(s).,10B,...,N,23.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2017,2017-03-21
4764,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,08/25/2016,Violations were cited in the following area(s).,06C,...,Y,19.0,B,08/25/2016,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2016,2016-08-25
373683,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,08/25/2016,Violations were cited in the following area(s).,10F,...,N,19.0,B,08/25/2016,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2016,2016-08-25
292739,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,08/25/2016,Violations were cited in the following area(s).,06A,...,Y,19.0,B,08/25/2016,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2016,2016-08-25
281223,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,08/25/2016,Violations were cited in the following area(s).,02B,...,Y,19.0,B,08/25/2016,Cycle Inspection / Re-inspection,40.762775,-73.805229,117100.0,2016,2016-08-25
232742,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,07/13/2016,Violations were cited in the following area(s).,06C,...,Y,30.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2016,2016-07-13
171695,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,07/13/2016,Violations were cited in the following area(s).,10I,...,N,30.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2016,2016-07-13
171433,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,07/13/2016,Violations were cited in the following area(s).,10F,...,N,30.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2016,2016-07-13
131351,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,07/13/2016,Violations were cited in the following area(s).,02G,...,Y,30.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2016,2016-07-13
82436,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,07/13/2016,Violations were cited in the following area(s).,06D,...,Y,30.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2016,2016-07-13
197001,41187577,HANSOL NUTRITION CENTER,Queens,16026,NORTHERN BOULEVARD,11358.0,Korean,07/13/2016,Violations were cited in the following area(s).,06A,...,Y,30.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.762775,-73.805229,117100.0,2016,2016-07-13

In [105]:
df18 = df18.drop(columns='Unnamed: 0')

In [109]:
df18.sort_values(by='CAMIS', ascending=False)

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,...,CRITICAL FLAG,SCORE,GRADE,GRADE DATE,INSPECTION TYPE,Latitude,Longitude,Census Tract,INSPECTION YEAR,IN-DATE
30692,50086910,SAMIR RESTAURANT,Brooklyn,696,CONEY ISLAND AVE,11218.0,Indian,12/27/2018,Violations were cited in the following area(s).,08A,...,N,48.0,NaN,NaN,Pre-permit (Non-operational) / Initial Inspection,40.640503,-73.969149,49200.0,2018,2018-12-27
84410,50086910,SAMIR RESTAURANT,Brooklyn,696,CONEY ISLAND AVE,11218.0,Indian,12/27/2018,Violations were cited in the following area(s).,06D,...,Y,48.0,NaN,NaN,Pre-permit (Non-operational) / Initial Inspection,40.640503,-73.969149,49200.0,2018,2018-12-27
124322,50086910,SAMIR RESTAURANT,Brooklyn,696,CONEY ISLAND AVE,11218.0,Indian,12/27/2018,Violations were cited in the following area(s).,04L,...,Y,48.0,NaN,NaN,Pre-permit (Non-operational) / Initial Inspection,40.640503,-73.969149,49200.0,2018,2018-12-27
125987,50086910,SAMIR RESTAURANT,Brooklyn,696,CONEY ISLAND AVE,11218.0,Indian,12/27/2018,Violations were cited in the following area(s).,05C,...,Y,48.0,NaN,NaN,Pre-permit (Non-operational) / Initial Inspection,40.640503,-73.969149,49200.0,2018,2018-12-27
28877,50086910,SAMIR RESTAURANT,Brooklyn,696,CONEY ISLAND AVE,11218.0,Indian,12/27/2018,Violations were cited in the following area(s).,10H,...,N,48.0,NaN,NaN,Pre-permit (Non-operational) / Initial Inspection,40.640503,-73.969149,49200.0,2018,2018-12-27
89240,50086790,NIUDDO,Queens,4142,MAIN ST,11355.0,Chinese,12/28/2018,Violations were cited in the following area(s).,10B,...,N,12.0,NaN,NaN,Pre-permit (Operational) / Initial Inspection,40.757088,-73.828972,84900.0,2018,2018-12-28
53282,50086790,NIUDDO,Queens,4142,MAIN ST,11355.0,Chinese,12/28/2018,Violations were cited in the following area(s).,05H,...,Y,12.0,NaN,NaN,Pre-permit (Operational) / Initial Inspection,40.757088,-73.828972,84900.0,2018,2018-12-28
39162,50086764,EL CLUB VALLE RESTAURANT,Bronx,352,E GUN HILL RD,10467.0,Spanish,12/19/2018,Violations were cited in the following area(s).,02B,...,Y,31.0,NaN,NaN,Pre-permit (Operational) / Initial Inspection,40.878759,-73.872779,42902.0,2018,2018-12-19
50995,50086764,EL CLUB VALLE RESTAURANT,Bronx,352,E GUN HILL RD,10467.0,Spanish,12/19/2018,Violations were cited in the following area(s).,08A,...,N,31.0,NaN,NaN,Pre-permit (Operational) / Initial Inspection,40.878759,-73.872779,42902.0,2018,2018-12-19
127532,50086764,EL CLUB VALLE RESTAURANT,Bronx,352,E GUN HILL RD,10467.0,Spanish,12/19/2018,Violations were cited in the following area(s).,04K,...,Y,31.0,NaN,NaN,Pre-permit (Operational) / Initial Inspection,40.878759,-73.872779,42902.0,2018,2018-12-19
13186,50086764,EL CLUB VALLE RESTAURANT,Bronx,352,E GUN HILL RD,10467.0,Spanish,12/19/2018,Violations were cited in the following area(s).,04A,...,Y,31.0,NaN,NaN,Pre-permit (Operational) / Initial Inspection,40.878759,-73.872779,42902.0,2018,2018-12-19
111097,50086764,EL CLUB VALLE RESTAURANT,Bronx,352,E GUN HILL RD,10467.0,Spanish,12/19/2018,Violations were cited in the following area(s).,08C,...,N,31.0,NaN,NaN,Pre-permit (Operational) / Initial Inspection,40.878759,-73.872779,42902.0,2018,2018-12-19
37410,50086764,EL CLUB VALLE RESTAURANT,Bronx,352,E GUN HILL RD,10467.0,Spanish,12/19/2018,Violations were cited in the following area(s).,04M,...,Y,31.0,NaN,NaN,Pre-permit (Operational) / Initial Inspection,40.878759,-73.872779,42902.0,2018,2018-12-19
43861,50086713,ABUELA ANTONIA RESTAURANT,Brooklyn,225,ROCKAWAY AVE,11233.0,Mexican,12/26/2018,Violations were cited in the following area(s).,06C,...,Y,13.0,NaN,NaN,Pre-permit (Non-operational) / Initial Inspection,40.674961,-73.911048,36501.0,2018,2018-12-26
30666,50086713,ABUELA ANTONIA RESTAURANT,Brooklyn,225,ROCKAWAY AVE,11233.0,Mexican,12/26/2018,Violations were cited in the following area(s).,10F,...,N,13.0,NaN,NaN,Pre-permit (Non-operational) / Initial Inspection,40.674961,-73.911048,36501.0,2018,2018-12-26
14712,50086704,CAFE ZAIYA,Manhattan,18,E 41ST ST,10017.0,Japanese,12/24/2018,Violations were cited in the following area(s).,02B,...,Y,26.0,NaN,NaN,Pre-permit (Operational) / Initial Inspection,40.752410,-73.980448,8200.0,2018,2018-12-24
53426,50086704,CAFE ZAIYA,Manhattan,18,E 41ST ST,10017.0,Japanese,12/24/2018,Violations were cited in the following area(s).,08A,...,N,26.0,NaN,NaN,Pre-permit (Operational) / Initial Inspection,40.752410,-73.980448,8200.0,2018,2018-12-24
3778,50086704,CAFE ZAIYA,Manhattan,18,E 41ST ST,10017.0,Japanese,12/24/2018,Violations were cited in the following area(s).,04L,...,Y,26.0,NaN,NaN,Pre-permit (Operational) / Initial Inspection,40.752410,-73.980448,8200.0,2018,2018-12-24
65970,50086704,CAFE ZAIYA,Manhattan,18,E 41ST ST,10017.0,Japanese,12/24/2018,Violations were cited in the following area(s).,05D,...,Y,26.0,NaN,NaN,Pre-permit (Operational) / Initial Inspection,40.752410,-73.980448,8200.0,2018,2018-12-24
48672,50086543,VERSAILLES PALACE,Queens,6334,AUSTIN ST,11374.0,Russian,12/20/2018,Violations were cited in the following area(s).,10F,...,N,7.0,A,12/20/2018,Pre-permit (Operational) / Initial Inspection,40.727728,-73.865095,69500.0,2018,2018-12-20
57097,50086543,VERSAILLES PALACE,Queens,6334,AUSTIN ST,11374.0,Russian,12/20/2018,Violations were cited in the following area(s).,06F,...,Y,7.0,A,12/20/2018,Pre-permit (Operational) / Initial Inspection,40.727728,-73.865095,69500.0,2018,2018-12-20
105766,50086525,KROK,Brooklyn,117,COLUMBIA ST,11231.0,Thai,12/19/2018,Violations were cited in the following area(s).,10F,...,N,32.0,NaN,NaN,Pre-permit (Non-operational) / Initial Inspection,40.687440,-74.001525,4700.0,2018,2018-12-19
100665,50086525,KROK,Brooklyn,117,COLUMBIA ST,11231.0,Thai,12/31/2018,Violations were cited in the following area(s).,10B,...,N,5.0,NaN,NaN,Pre-permit (Non-operational) / Re-inspection,40.687440,-74.001525,4700.0,2018,2018-12-31
58811,50086525,KROK,Brooklyn,117,COLUMBIA ST,11231.0,Thai,12/31/2018,Violations were cited in the following area(s).,10F,...,N,5.0,NaN,NaN,Pre-permit (Non-operational) / Re-inspection,40.687440,-74.001525,4700.0,2018,2018-12-31
24432,50086525,KROK,Brooklyn,117,COLUMBIA ST,11231.0,Thai,12/19/2018,Violations were cited in the following area(s).,10B,...,N,32.0,NaN,NaN,Pre-permit (Non-operational) / Initial Inspection,40.687440,-74.001525,4700.0,2018,2018-12-19
47433,50086525,KROK,Brooklyn,117,COLUMBIA ST,11231.0,Thai,12/19/2018,Violations were cited in the following area(s).,05C,...,Y,32.0,NaN,NaN,Pre-permit (Non-operational) / Initial Inspection,40.687440,-74.001525,4700.0,2018,2018-12-19
84229,50086501,Strawberry Garden,Manhattan,98,NAGLE AVE,10040.0,"Juice, Smoothies, Fruit Salads",12/31/2018,Violations were cited in the following area(s).,10H,...,N,7.0,NaN,NaN,Pre-permit (Non-operational) / Initial Inspection,40.860587,-73.927497,28500.0,2018,2018-12-31
94720,50086501,Strawberry Garden,Manhattan,98,NAGLE AVE,10040.0,"Juice, Smoothies, Fruit Salads",12/31/2018,Violations were cited in the following area(s).,10E,...,N,7.0,NaN,NaN,Pre-permit (Non-operational) / Initial Inspection,40.860587,-73.927497,28500.0,2018,2018-12-31
16242,50086501,Strawberry Garden,Manhattan,98,NAGLE AVE,10040.0,"Juice, Smoothies, Fruit Salads",12/31/2018,Violations were cited in the following area(s).,10B,...,N,7.0,NaN,NaN,Pre-permit (Non-operational) / Initial Inspection,40.860587,-73.927497,28500.0,2018,2018-12-31
82057,50086456,Pizza Supreme,Bronx,5959,BROADWAY,10463.0,Pizza/Italian,12/18/2018,Violations were cited in the following area(s).,10F,...,N,2.0,NaN,NaN,Pre-permit (Non-operational) / Initial Inspection,40.888948,-73.898532,28500.0,2018,2018-12-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36049,40361322,CARVEL ICE CREAM,Queens,26515,HILLSIDE AVENUE,11004.0,"Ice Cream, Gelato, Yogurt, Ices",07/12/2018,Violations were cited in the following area(s).,10F,...,N,25.0,B,07/12/2018,Cycle Inspection / Re-inspection,40.738368,-73.703511,157901.0,2018,2018-07-12
114930,40360076,CARVEL ICE CREAM,Brooklyn,203,CHURCH AVENUE,11218.0,"Ice Cream, Gelato, Yogurt, Ices",03/20/2018,Violations were cited in the following area(s).,08A,...,N,13.0,A,03/20/2018,Cycle Inspection / Initial Inspection,40.643330,-73.978189,49600.0,2018,2018-03-20
82970,40360076,CARVEL ICE CREAM,Brooklyn,203,CHURCH AVENUE,11218.0,"Ice Cream, Gelato, Yogurt, Ices",03/20/2018,Violations were cited in the following area(s).,10I,...,N,13.0,A,03/20/2018,Cycle Inspection / Initial Inspection,40.643330,-73.978189,49600.0,2018,2018-03-20
91245,40360076,CARVEL ICE CREAM,Brooklyn,203,CHURCH AVENUE,11218.0,"Ice Cream, Gelato, Yogurt, Ices",03/20/2018,Violations were cited in the following area(s).,04K,...,Y,13.0,A,03/20/2018,Cycle Inspection / Initial Inspection,40.643330,-73.978189,49600.0,2018,2018-03-20
40225,40360045,SEUDA FOODS,Brooklyn,705,KINGS HIGHWAY,11223.0,Jewish/Kosher,11/27/2018,Violations were cited in the following area(s).,10F,...,N,3.0,A,11/27/2018,Cycle Inspection / Initial Inspection,40.606187,-73.965466,41800.0,2018,2018-11-27
50231,40359705,NATHAN'S FAMOUS,Brooklyn,1310,SURF AVENUE,11224.0,Hotdogs,03/07/2018,Violations were cited in the following area(s).,06C,...,Y,10.0,A,03/07/2018,Cycle Inspection / Initial Inspection,40.575537,-73.981652,35200.0,2018,2018-03-07
34442,40359705,NATHAN'S FAMOUS,Brooklyn,1310,SURF AVENUE,11224.0,Hotdogs,03/07/2018,Violations were cited in the following area(s).,10F,...,N,10.0,A,03/07/2018,Cycle Inspection / Initial Inspection,40.575537,-73.981652,35200.0,2018,2018-03-07
55074,40359480,1 EAST 66TH STREET KITCHEN,Manhattan,1,EAST 66 STREET,10065.0,American,09/28/2018,Violations were cited in the following area(s).,06D,...,Y,7.0,A,09/28/2018,Cycle Inspection / Initial Inspection,40.768547,-73.969581,12200.0,2018,2018-09-28
39662,40359480,1 EAST 66TH STREET KITCHEN,Manhattan,1,EAST 66 STREET,10065.0,American,09/28/2018,Violations were cited in the following area(s).,10F,...,N,7.0,A,09/28/2018,Cycle Inspection / Initial Inspection,40.768547,-73.969581,12200.0,2018,2018-09-28
21697,40357217,WILD ASIA,Bronx,2300,SOUTHERN BOULEVARD,10460.0,American,05/31/2018,Violations were cited in the following area(s).,10B,...,N,5.0,A,05/31/2018,Cycle Inspection / Initial Inspection,40.850556,-73.882451,33400.0,2018,2018-05-31
1441,40357217,WILD ASIA,Bronx,2300,SOUTHERN BOULEVARD,10460.0,American,05/31/2018,Violations were cited in the following area(s).,10F,...,N,5.0,A,05/31/2018,Cycle Inspection / Initial Inspection,40.850556,-73.882451,33400.0,2018,2018-05-31
57872,40356731,TASTE THE TROPICS ICE CREAM,Brooklyn,1839,NOSTRAND AVENUE,11226.0,"Ice Cream, Gelato, Yogurt, Ices",05/16/2018,Violations were cited in the following area(s).,10F,...,N,13.0,A,05/16/2018,Cycle Inspection / Initial Inspection,40.640795,-73.948488,82800.0,2018,2018-05-16
65052,40356731,TASTE THE TROPICS ICE CREAM,Brooklyn,1839,NOSTRAND AVENUE,11226.0,"Ice Cream, Gelato, Yogurt, Ices",05/16/2018,Violations were cited in the following area(s).,04L,...,Y,13.0,A,05/16/2018,Cycle Inspection / Initial Inspection,40.640795,-73.948488,82800.0,2018,2018-05-16
89084,40356731,TASTE THE TROPICS ICE CREAM,Brooklyn,1839,NOSTRAND AVENUE,11226.0,"Ice Cream, Gelato, Yogurt, Ices",05/16/2018,Violations were cited in the following area(s).,08C,...,N,13.0,A,05/16/2018,Cycle Inspection / Initial Inspection,40.640795,-73.948488,82800.0,2018,2018-05-16
26252,40356731,TASTE THE TROPICS ICE CREAM,Brooklyn,1839,NOSTRAND AVENUE,11226.0,"Ice Cream, Gelato, Yogurt, Ices",05/16/2018,Violations were cited in the following area(s).,08A,...,N,13.0,A,05/16/2018,Cycle Inspection / Initial Inspection,40.640795,-73.948488,82800.0,2018,2018-05-16
88604,40356483,WILKEN'S FINE FOOD,Brooklyn,7114,AVENUE U,11234.0,Delicatessen,05/10/2018,Violations were cited in the following area(s).,06C,...,Y,13.0,A,05/10/2018,Cycle Inspection / Initial Inspection,40.620112,-73.906989,70000.0,2018,2018-05-10
67016,40356483,WILKEN'S FINE FOOD,Brooklyn,7114,AVENUE U,11234.0,Delicatessen,05/10/2018,Violations were cited in the following area(s).,10F,...,N,13.0,A,05/10/2018,Cycle Inspection / Initial Inspection,40.620112,-73.906989,70000.0,2018,2018-05-10
72544,40356151,BRUNOS ON THE BOULEVARD,Queens,8825,ASTORIA BOULEVARD,11369.0,American,10/06/2018,Violations were cited in the following area(s).,04N,...,Y,40.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.763971,-73.880973,32900.0,2018,2018-10-06
53217,40356151,BRUNOS ON THE BOULEVARD,Queens,8825,ASTORIA BOULEVARD,11369.0,American,10/06/2018,Violations were cited in the following area(s).,08A,...,N,40.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.763971,-73.880973,32900.0,2018,2018-10-06
76500,40356151,BRUNOS ON THE BOULEVARD,Queens,8825,ASTORIA BOULEVARD,11369.0,American,10/06/2018,Violations were cited in the following area(s).,04H,...,Y,40.0,NaN,NaN,Cycle Inspection / Initial Inspection,40.763971,-73.880973,32900.0,2018,2018-10-06
95286,40356018,RIVIERA CATERERS,Brooklyn,2780,STILLWELL AVENUE,11224.0,American,10/30/2018,Violations were cited in the following area(s).,10F,...,N,10.0,A,10/30/2018,Cycle Inspection / Initial Inspection,40.579920,-73.982090,34800.0,2018,2018-10-30
124914,40356018,RIVIERA CATERERS,Brooklyn,2780,STILLWELL AVENUE,11224.0,American,10/30/2018,Violations were cited in the following area(s).,06D,...,Y,10.0,A,10/30/2018,Cycle Inspection / Initial Inspection,40.579920,-73.982090,34800.0,2018,2018-10-30
119530,30191841,DJ REYNOLDS PUB AND RESTAURANT,Manhattan,351,WEST 57 STREET,10019.0,Irish,05/16/2018,Violations were cited in the following area(s).,08A,...,N,12.0,A,05/16/2018,Cycle Inspection / Initial Inspection,40.767326,-73.984310,13900.0,2018,2018-05-16
13238,30191841,DJ REYNOLDS PUB AND RESTAURANT,Manhattan,351,WEST 57 STREET,10019.0,Irish,05/16/2018,Violations were cited in the following area(s).,10F,...,N,12.0,A,05/16/2018,Cycle Inspection / Initial Inspection,40.767326,-73.984310,13900.0,2018,2018-05-16
71004,30191841,DJ REYNOLDS PUB AND RESTAURANT,Manhattan,351,WEST 57 STREET,10019.0,Irish,05/16/2018,Violations were cited in the following area(s).,04L,...,Y,12.0,A,05/16/2018,Cycle Inspection / Initial Inspection,40.767326,-73.984310,13900.0,2018,2018-05-16
58610,30112340,WENDY'S,Brooklyn,469,FLATBUSH AVENUE,11225.0,Hamburgers,03/13/2018,Violations were cited in the following area(s).,04L,...,Y,12.0,A,03/13/2018,Cycle Inspection / Initial Inspection,40.662652,-73.962081,32700.0,2018,2018-03-13
122720,30112340,WENDY'S,Brooklyn,469,FLATBUSH AVENUE,11225.0,Hamburgers,03/13/2018,Violations were cited in the following area(s).,10B,...,N,12.0,A,03/13/2018,Cycle Inspection / Initial Inspection,40.662652,-73.962081,32700.0,2018,2018-03-13
21651,30112340,WENDY'S,Brooklyn,469,FLATBUSH AVENUE,11225.0,Hamburgers,03/13/2018,Violations were cited in the following area(s).,08A,...,N,12.0,A,03/13/2018,Cycle Inspection / Initial Inspection,40.662652,-73.962081,32700.0,2018,2018-03-13
79050,30075445,MORRIS PARK BAKE SHOP,Bronx,1007,MORRIS PARK AVE,10462.0,Bakery,05/11/2018,Violations were cited in the following area(s).,08C,...,N,5.0,A,05/11/2018,Cycle Inspection / Initial Inspection,40.848231,-73.855972,25200.0,2018,2018-05-11
83638,30075445,MORRIS PARK BAKE SHOP,Bronx,1007,MORRIS PARK AVE,10462.0,Bakery,05/11/2018,Violations were cited in the following area(s).,10F,...,N,5.0,A,05/11/2018,Cycle Inspection / Initial Inspection,40.848231,-73.855972,25200.0,2018,2018-05-11

In [114]:
df18.groupby(['CAMIS','IN-DATE']).count()

                     DBA  BORO  BUILDING  STREET  ZIPCODE  \
CAMIS    IN-DATE
30075445 2018-05-11    2     2         2       2        2
30112340 2018-03-13    3     3         3       3        3
30191841 2018-05-16    3     3         3       3        3
40356018 2018-10-30    2     2         2       2        2
40356151 2018-10-06    3     3         3       3        3
40356483 2018-05-10    2     2         2       2        2
40356731 2018-05-16    4     4         4       4        4
40357217 2018-05-31    2     2         2       2        2
40359480 2018-09-28    2     2         2       2        2
40359705 2018-03-07    2     2         2       2        2
40360045 2018-11-27    1     1         1       1        1
40360076 2018-03-20    3     3         3       3        3
40361322 2018-03-28    4     4         4       4        4
         2018-07-12    4     4         4       4        4
40361618 2018-01-24    3     3         3       3        3
         2018-06-05    3     3         3       3        3
40361998 2018-07-18    1     1         1       1        1
40362264 2018-05-16    4     4         4       4        4
         2018-07-02    4     4         4       4        4
         2018-07-10    3     3         3       3        3
         2018-11-07    7     7         7       7        7
         2018-12-18    2     2         2       2        2
40362274 2018-06-04    5     5         5       5        5
         2018-07-09    5     5         5       5        5
40362432 2018-05-03    3     3         3       3        3
         2018-06-21    3     3         3       3        3
40362715 2018-04-13    4     4         4       4        4
         2018-05-25    1     1         1       1        1
         2018-10-17    5     5         5       5        5
         2018-10-24    2     2         2       2        2
...                  ...   ...       ...     ...      ...
50086146 2018-12-18    8     8         8       8        8
         2018-12-21    2     2         2       2        2
50086154 2018-12-27    7     7         7       7        7
50086162 2018-12-05    2     2         2       2        2
50086204 2018-11-20    3     3         3       3        3
         2018-12-20    5     5         5       5        5
50086205 2018-12-10    4     4         4       4        4
50086207 2018-11-20    3     3         3       3        3
50086222 2018-12-19    3     3         3       3        3
50086291 2018-12-03    2     2         2       2        2
50086302 2018-11-28    3     3         3       3        3
         2018-12-20    2     2         2       2        2
50086366 2018-12-17    5     5         5       5        5
50086378 2018-12-12    1     1         1       1        1
50086396 2018-12-31    2     2         2       2        2
50086397 2018-12-26    5     5         5       5        5
50086406 2018-12-13    5     5         5       5        5
         2018-12-21    3     3         3       3        3
50086408 2018-12-17    4     4         4       4        4
50086431 2018-12-10    3     3         3       3        3
50086456 2018-12-18    1     1         1       1        1
50086501 2018-12-31    3     3         3       3        3
50086525 2018-12-19    3     3         3       3        3
         2018-12-31    2     2         2       2        2
50086543 2018-12-20    2     2         2       2        2
50086704 2018-12-24    4     4         4       4        4
50086713 2018-12-26    2     2         2       2        2
50086764 2018-12-19    6     6         6       6        6
50086790 2018-12-28    2     2         2       2        2
50086910 2018-12-27    5     5         5       5        5

                     CUISINE DESCRIPTION  INSPECTION DATE  ACTION  \
CAMIS    IN-DATE
30075445 2018-05-11                    2                2       2
30112340 2018-03-13                    3                3       3
30191841 2018-05-16                    3                3       3
40356018 2018-10-30                    2                2       2
40356151 2018-10-06                    3                3       3
40356483 2018-05-10                    2                2       2
40356731 2018-05-16                    4                4       4
40357217 2018-05-31                    2                2       2
40359480 2018-09-28                    2                2       2
40359705 2018-03-07                    2                2       2
40360045 2018-11-27                    1                1       1
40360076 2018-03-20                    3                3       3
40361322 2018-03-28                    4                4       4
         2018-07-12                    4                4       4
40361618 2018-01-24                    3                3       3
         2018-06-05                    3                3       3
40361998 2018-07-18                    1                1       1
40362264 2018-05-16                    4                4       4
         2018-07-02                    4                4       4
         2018-07-10                    3                3       3
         2018-11-07                    7                7       7
         2018-12-18                    2                2       2
40362274 2018-06-04                    5                5       5
         2018-07-09                    5                5       5
40362432 2018-05-03                    3                3       3
         2018-06-21                    3                3       3
40362715 2018-04-13                    4                4       4
         2018-05-25                    1                1       1
         2018-10-17                    5                5       5
         2018-10-24                    2                2       2
...                                  ...              ...     ...
50086146 2018-12-18                    8                8       8
         2018-12-21                    2                2       2
50086154 2018-12-27                    7                7       7
50086162 2018-12-05                    2                2       2
50086204 2018-11-20                    3                3       3
         2018-12-20                    5                5       5
50086205 2018-12-10                    4                4       4
50086207 2018-11-20                    3                3       3
50086222 2018-12-19                    3                3       3
50086291 2018-12-03                    2                2       2
50086302 2018-11-28                    3                3       3
         2018-12-20                    2                2       2
50086366 2018-12-17                    5                5       5
50086378 2018-12-12                    1                1       1
50086396 2018-12-31                    2                2       2
50086397 2018-12-26                    5                5       5
50086406 2018-12-13                    5                5       5
         2018-12-21                    3                3       3
50086408 2018-12-17                    4                4       4
50086431 2018-12-10                    3                3       3
50086456 2018-12-18                    1                1       1
50086501 2018-12-31                    3                3       3
50086525 2018-12-19                    3                3       3
         2018-12-31                    2                2       2
50086543 2018-12-20                    2                2       2
50086704 2018-12-24                    4                4       4
50086713 2018-12-26                    2                2       2
50086764 2018-12-19                    6                6       6
50086790 2018-12-28                    2                2       2
50086910 2018-12-27                    5                5       5

                     VIOLATION CODE  VIOLATION DESCRIPTION  CRITICAL FLAG  \
CAMIS    IN-DATE
30075445 2018-05-11               2                      2              2
30112340 2018-03-13               3                      3              3
30191841 2018-05-16               3                      3              3
40356018 2018-10-30               2                      2              2
40356151 2018-10-06               3                      3              3
40356483 2018-05-10               2                      2              2
40356731 2018-05-16               4                      4              4
40357217 2018-05-31               2                      2              2
40359480 2018-09-28               2                      2              2
40359705 2018-03-07               2                      2              2
40360045 2018-11-27               1                      1              1
40360076 2018-03-20               3                      3              3
40361322 2018-03-28               4                      4              4
         2018-07-12               4                      4              4
40361618 2018-01-24               3                      3              3
         2018-06-05               3                      3              3
40361998 2018-07-18               1                      1              1
40362264 2018-05-16               4                      4              4
         2018-07-02               4                      4              4
         2018-07-10               3                      3              3
         2018-11-07               7                      7              7
         2018-12-18               2                      2              2
40362274 2018-06-04               5                      5              5
         2018-07-09               5                      5              5
40362432 2018-05-03               3                      3              3
         2018-06-21               3                      3              3
40362715 2018-04-13               4                      4              4
         2018-05-25               1                      1              1
         2018-10-17               5                      5              5
         2018-10-24               2                      2              2
...                             ...                    ...            ...
50086146 2018-12-18               8                      8              8
         2018-12-21               2                      2              2
50086154 2018-12-27               7                      7              7
50086162 2018-12-05               2                      2              2
50086204 2018-11-20               3                      3              3
         2018-12-20               5                      5              5
50086205 2018-12-10               4                      4              4
50086207 2018-11-20               3                      3              3
50086222 2018-12-19               3                      3              3
50086291 2018-12-03               2                      2              2
50086302 2018-11-28               3                      3              3
         2018-12-20               2                      2              2
50086366 2018-12-17               5                      5              5
50086378 2018-12-12               1                      1              1
50086396 2018-12-31               2                      2              2
50086397 2018-12-26               5                      5              5
50086406 2018-12-13               5                      5              5
         2018-12-21               3                      2              2
50086408 2018-12-17               4                      4              4
50086431 2018-12-10               3                      3              3
50086456 2018-12-18               1                      1              1
50086501 2018-12-31               3                      3              3
50086525 2018-12-19               3                      3              3
         2018-12-31               2                      2              2
50086543 2018-12-20               2                      2              2
50086704 2018-12-24               4                      4              4
50086713 2018-12-26               2                      2              2
50086764 2018-12-19               6                      6              6
50086790 2018-12-28               2                      2              2
50086910 2018-12-27               5                      5              5

                     SCORE  GRADE  GRADE DATE  INSPECTION TYPE  Latitude  \
CAMIS    IN-DATE
30075445 2018-05-11      2      2           2                2         2
30112340 2018-03-13      3      3           3                3         3
30191841 2018-05-16      3      3           3                3         3
40356018 2018-10-30      2      2           2                2         2
40356151 2018-10-06      3      0           0                3         3
40356483 2018-05-10      2      2           2                2         2
40356731 2018-05-16      4      4           4                4         4
40357217 2018-05-31      2      2           2                2         2
40359480 2018-09-28      2      2           2                2         2
40359705 2018-03-07      2      2           2                2         2
40360045 2018-11-27      1      1           1                1         1
40360076 2018-03-20      3      3           3                3         3
40361322 2018-03-28      4      0           0                4         4
         2018-07-12      4      4           4                4         4
40361618 2018-01-24      3      3           3                3         3
         2018-06-05      3      3           3                3         3
40361998 2018-07-18      1      1           1                1         1
40362264 2018-05-16      4      0           0                4         4
         2018-07-02      4      4           4                4         4
         2018-07-10      3      0           0                3         3
         2018-11-07      6      0           0                7         7
         2018-12-18      2      2           2                2         2
40362274 2018-06-04      5      0           0                5         5
         2018-07-09      5      5           5                5         5
40362432 2018-05-03      3      0           0                3         3
         2018-06-21      3      3           3                3         3
40362715 2018-04-13      4      0           0                4         4
         2018-05-25      1      1           1                1         1
         2018-10-17      5      0           0                5         5
         2018-10-24      2      0           0                2         2
...                    ...    ...         ...              ...       ...
50086146 2018-12-18      8      0           0                8         8
         2018-12-21      2      2           2                2         2
50086154 2018-12-27      7      0           0                7         7
50086162 2018-12-05      2      0           0                2         2
50086204 2018-11-20      3      0           0                3         3
         2018-12-20      5      5           5                5         5
50086205 2018-12-10      4      0           0                4         4
50086207 2018-11-20      2      2           2                3         3
50086222 2018-12-19      3      0           0                3         3
50086291 2018-12-03      2      0           0                2         2
50086302 2018-11-28      3      0           0                3         3
         2018-12-20      2      2           2                2         2
50086366 2018-12-17      5      0           0                5         5
50086378 2018-12-12      1      0           0                1         1
50086396 2018-12-31      2      2           2                2         2
50086397 2018-12-26      4      0           0                5         5
50086406 2018-12-13      5      0           0                5         5
         2018-12-21      3      3           3                3         3
50086408 2018-12-17      3      0           0                4         4
50086431 2018-12-10      3      3           3                3         3
50086456 2018-12-18      1      0           0                1         1
50086501 2018-12-31      3      0           0                3         3
50086525 2018-12-19      3      0           0                3         3
         2018-12-31      2      0           0                2         2
50086543 2018-12-20      2      2           2                2         2
50086704 2018-12-24      4      0           0                4         4
50086713 2018-12-26      2      0           0                2         2
50086764 2018-12-19      6      0           0                6         6
50086790 2018-12-28      2      0           0                2         2
50086910 2018-12-27      5      0           0                5         5

                     Longitude  Census Tract  INSPECTION YEAR
CAMIS    IN-DATE
30075445 2018-05-11          2             2                2
30112340 2018-03-13          3             3                3
30191841 2018-05-16          3             3                3
40356018 2018-10-30          2             2                2
40356151 2018-10-06          3             3                3
40356483 2018-05-10          2             2                2
40356731 2018-05-16          4             4                4
40357217 2018-05-31          2             2                2
40359480 2018-09-28          2             2                2
40359705 2018-03-07          2             2                2
40360045 2018-11-27          1             1                1
40360076 2018-03-20          3             3                3
40361322 2018-03-28          4             4                4
         2018-07-12          4             4                4
40361618 2018-01-24          3             3                3
         2018-06-05          3             3                3
40361998 2018-07-18          1             1                1
40362264 2018-05-16          4             4                4
         2018-07-02          4             4                4
         2018-07-10          3             3                3
         2018-11-07          7             7                7
         2018-12-18          2             2                2
40362274 2018-06-04          5             5                5
         2018-07-09          5             5                5
40362432 2018-05-03          3             3                3
         2018-06-21          3             3                3
40362715 2018-04-13          4             4                4
         2018-05-25          1             1                1
         2018-10-17          5             5                5
         2018-10-24          2             2                2
...                        ...           ...              ...
50086146 2018-12-18          8             8                8
         2018-12-21          2             2                2
50086154 2018-12-27          7             7                7
50086162 2018-12-05          2             2                2
50086204 2018-11-20          3             3                3
         2018-12-20          5             5                5
50086205 2018-12-10          4             4                4
50086207 2018-11-20          3             3                3
50086222 2018-12-19          3             3                3
50086291 2018-12-03          2             2                2
50086302 2018-11-28          3             3                3
         2018-12-20          2             2                2
50086366 2018-12-17          5             5                5
50086378 2018-12-12          1             1                1
50086396 2018-12-31          2             2                2
50086397 2018-12-26          5             5                5
50086406 2018-12-13          5             5                5

In [65]:
df18.drop(columns=['INSPECTION DATE',]

Index(['Unnamed: 0', 'CAMIS', 'DBA', 'BORO', 'BUILDING', 'STREET', 'ZIPCODE',
       'CUISINE DESCRIPTION', 'INSPECTION DATE', 'ACTION', 'VIOLATION CODE',
       'VIOLATION DESCRIPTION', 'CRITICAL FLAG', 'SCORE', 'GRADE',
       'GRADE DATE', 'INSPECTION TYPE', 'Latitude', 'Longitude',
       'Census Tract', 'INSPECTION YEAR', 'IN-DATE'],
      dtype='object')

In [151]:
# #df_test["Codes_List"] = 
# df.groupby(by=['CAMIS', 'DBA', 'INSPECTION YEAR','IN-DATE','GRADE DATE','BORO', 'BUILDING', 'STREET', 'ZIPCODE',
#        'CUISINE DESCRIPTION', 'ACTION', 'SCORE', 'GRADE', 'INSPECTION TYPE', 'Latitude', 'Longitude',
#        'Census Tract'])['VIOLATION CODE'].value_counts().unstack() #.agg(lambda x: ', '.join(set(x)))

In [129]:
df_test["Total_Violations"] = df.groupby(by=['CAMIS', 'DBA', 'INSPECTION YEAR','IN-DATE','GRADE DATE','BORO', 'BUILDING', 'STREET', 'ZIPCODE',
       'CUISINE DESCRIPTION', 'ACTION', 'SCORE', 'GRADE', 'INSPECTION TYPE', 'Latitude', 'Longitude',
       'Census Tract']).count()["VIOLATION CODE"]

In [153]:
df_test.reset_index(inplace=True)

In [157]:
df_test = df_test.drop(columns=['INSPECTION DATE', 'VIOLATION CODE', 'VIOLATION DESCRIPTION','CRITICAL FLAG', 'Codes_List'])

In [159]:
df_test.shape

(81398, 18)